.

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,25 +1,47 @@
 #!/usr/bin/env bash
-# Customizing a 404-error_page
+# Install nginx on your web-01
+# server
+# Nginx should be listening on port 80
+# When querying Nginx at its root / with a GET request
+# (requesting a page) using curl,
+# it must return a page that contains the string Hello World!
 
-# Updating Packages before performing installations
-sudo apt-get update
-sudo apt-get install -y nginx
+# Bash script that configures a new Ubuntu machine
+# to respect above requirements (this script will be run on the server itself)
+# You can’t use systemctl for restarting nginx
 
-# Creating an index.html page
-echo "Hello World!" | sudo tee /var/www/html/index.html
+# Update package lists to get the latest versions of packages
+apt-get update
 
-# Performing a "moved permanently redirection" (301)
-new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
-sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default
+# Check if nginx is not installed by verifying if its executable is not found
+if ! [ -x "$(command -v nginx)" ]; then
 
-# Creating a 404 Custom error page
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
-new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
+  # Install nginx package silently (-y) without prompting for confirmation
+  apt-get install -y nginx
+fi
 
-sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
+# Allow incoming HTTP traffic through the firewall for Nginx
+ufw allow 'Nginx HTTP'
 
-# Testing configurations for syntax errors
-sudo nginx -t
+# Write "Hello World!" to the default HTML file served by Nginx
+echo "Hello World!" > /var/www/html/index.nginx-debian.html
 
-# restart nginx after implementing changes
-sudo service nginx restart
+# Configure your Nginx server so that /redirect_me is redirecting to another page.
+sudo sed -i "/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }" /etc/nginx/sites-available/default
+
+# Configure your Nginx server to have a custom 404 page
+# that contains the string Ceci n'est pas une page.
+echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
+
+# Check if custom configuration already exists in Nginx server configuration
+if ! grep -q "error_page 404 /error_404.html;" /etc/nginx/sites-available/default; then
+  # Modify the Nginx default server configuration
+  sudo sed -i '/server_name _;/a \
+          error_page 404 /error_404.html;\n \
+          location = /error_404.html {\n \
+              root /var/www/html;\n \
+          }\n' /etc/nginx/sites-available/default
+fi 
+
+# Start the Nginx service
+service nginx start
